### ISSUE TITLE
NoSuchMethodError running tests

### ISSUE THREAD

**Issue by brianegan** [dart-lang/test#556]
Hello! I'm contributing a bit to [RxDart](https://github.com/ReactiveX/rxdart), and ran into a problem when I upgraded from v0.12.19 to v0.12.20 of this package. I'm not sure if this is my bad or a bug in this package, but some instructions told me to file a bug here, and I thought I'd do just that if it helps! Thanks for any assistance :)

Reproduction steps:

  1. Clone [RxDart](https://github.com/ReactiveX/rxdart) repo
  2. Enter directory
  3. `pub get`
  4. `pub run test test/rxdart_test.dart` -- everything should work fine with 0.12.19
  5. Bump test version to `0.12.20` in the `pubspec.yaml` file
  6. re-run `pub run test test/rxdart_test.dart` -- experience stacktrace

p.s. Those new stream matchers are so good!!!

### Stacktrace

```
BMO lab/rxdart ‹master*› » pub run test test/rxdart_test.dart

00:08 +245: rx.ReplaySubject.error                                                                 The method 'catchError' was called on null.
Receiver: null
Tried calling: catchError(Closure: (dynamic, dynamic) => dynamic)
dart:core                                                 Object.noSuchMethod
package:test/src/runner/plugin/platform_helpers.dart 113  deserializeSuite.<async>.<fn>
package:test/src/runner/runner_suite.dart 113             RunnerSuiteController._close.<fn>.<async>

This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
Unhandled exception:
NoSuchMethodError: The method 'catchError' was called on null.
Receiver: null
Tried calling: catchError(Closure: (dynamic, dynamic) => dynamic)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      deserializeSuite.<deserializeSuite_async_body>.<anonymous closure> (package:test/src/runner/plugin/platform_helpers.dart:113)
#3      RunnerSuiteController._close.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/runner/runner_suite.dart:113)
#4      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#5      _rootRun (dart:async/zone.dart:1150)
#6      _CustomZone.run (dart:async/zone.dart:1026)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:953)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)                                                         
```

**Comment by nex3** [comment]
I think this is caused by a bogus version constraint. If you run `pub upgrade stream_channel` it should work again.

**Comment by brianegan** [comment]
`pub upgrade stream_channel` fixed it right up. Thanks for the ⚡️quick fix!
