### ISSUE TITLE
0.12.5 crashes trying to run map function on null object

### ISSUE THREAD

**Issue by alextech** [dart-lang/test#354]
Since upgrading to 0.12.5 from 0.12.4 test runner exits with 

```
 The null object does not have a method 'map'.

 NoSuchMethodError: method not found: 'map'
 Receiver: null
 Arguments: [Closure: (dynamic) => dynamic]
 dart:isolate  _RawReceivePortImpl._handleMessage
```

There are no line numbers or file names to track down what dependency causes an issue so I am not sure what code sample to submit at this point for you to reproduce it. Any idea how to narrow this down?

**Comment by nex3** [comment]
What Dart version are you using? What's the smallest test file you can create that still exhibits this behavior? What flags are you passing to the test runner?

**Comment by francislr** [comment]
I think I have the same error when I run the test command for dartium or content-shell.

For the following code :
```
import "package:test/test.dart";

void main() {
  group("int", () {
    test(".remainder() returns the remainder of division", () {
      expect(11.remainder(3), equals(2));
    });

    test(".toRadixString() returns a hex string", () {
      expect(11.toRadixString(16), equals("b"));
    });
  });
}
```
I run the command :
```
~/project/dummy $ pub run test -p dartium
00:01 +0 -1: loading test/dummy_test.dart                                                          
  Failed to load "test/dummy_test.dart":
  No constructor 'List.unmodifiable' declared in class 'List'.
  
  NoSuchMethodError: method not found: 'List.unmodifiable'
  Receiver: Type: class 'List'
  Arguments: [Instance(length:2) of '_GrowableList']
  package:test         group
  dummy_test.dart 4:8  main
  
00:01 +0 -1: Some tests failed.
```

When I run using the vm :
```
~/project/dummy $ pub run test
00:00 +2: All tests passed!
```

Test package version : 0.12.5
Dart VM version : 1.13.0-dev.7.6 (Fri Oct 30 22:21:50 2015) on "linux_x64"

**Comment by nex3** [comment]
@francislr That's not the same error; the original error is "The null object does not have a method 'map'", and yours is "No constructor 'List.unmodifiable' declared in class 'List'".

According to [the Dart SDK changelog](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#core-library-changes-5), `List.unmodifiable` was added in Dart 1.11, so I can't imagine why it wouldn't be present in your build of 1.13.0-dev.7.6. My best guess is that your pub version is out-of-date; what happens if you run `pub --version`?

**Comment by francislr** [comment]
@nex3 At first I thought the problem was related to this thread. As you said, List.unmodifiable was recently added. My Dartium and content_shell wasn't updated... I've solved by upgrading to latest version.
Thanks for the help

**Comment by matanlurey** [comment]
Dartium and Content Shell have been removed from the SDK.
